projects:
  [
    {
      name: jguard1,
      repositoryUrl: https://github.com/mmohiesen96/jguard.git,
      filesToValidate: [.gitignore, pom.xml, test.txt],
      propertiesToValidate: [repositoryUrls, persistPath]
    },
  ]
persistPath: /Users/moh/jguard
