projects:
  [
    {
      name: jguard,
      repositoryUrl: https://github.com/mmohiesen96/jguard.git,
      filesToValidate: [.gitignore, pom.xml],
      propertiesToValidate: [repositoryUrls, persistPath]
    },
    {
      name: jguard,
      repositoryUrl: https://github.com/mmohiesen96/jguard.git,
      filesToValidate: [.abood, pom.xml],
      propertiesToValidate: [repositoryUrls, persistPath]
    },
  ]
persistPath: /Users/abdfrehat/
