projects:
  [
    {
      name: jguard1,
      repositoryUrl: https://github.com/mmohiesen96/jguard.git,
      filesToValidate: [ .gitignore, pom.xml ],
      propertiesToValidate: [ repositoryUrls, com.p.p ]
    }
  ]
persistPath: /Users/moh/jguard
