projects:
  [
    {
      name: jguard1,
      repositoryUrl: https://github.com/mmohiesen96/jguard.git,
      filesToValidate: [ .gitignore, pom.xml ],
      propertiesToValidate: [ logging.info, org.spring.exception.info ]
    }
  ]
persistPath: /Users/moh/jguard
