repositoryUrls: [
  https://github.com/mmohiesen96/jguard.git
]
persistPath: /Users/abdfrehat/Frehat/repos
filesToValidate: [
  .gitignore,
  pom.xml
]
propertiesToValidate: [
  repositoryUrls,
  persistPath
]